const DEFAULT_JIRA_COLUMNS = 'key,summary,created,priority,status';
const DEFAULT_JIRA_ISSUE_COUNT = 10;
const MAIN_JIRA_LABEL = "CI";

export {DEFAULT_JIRA_COLUMNS, DEFAULT_JIRA_ISSUE_COUNT, MAIN_JIRA_LABEL};
